export const PROFISSOES = [
  { value: "0", label: "Não informada" },
  { value: "1", label: "Acondicionador" },
  { value: "2", label: "Açougueiro" },
  { value: "3", label: "Adestrador de Animais" },
  { value: "4", label: "Administrador" },
  { value: "5", label: "Administrador de Empresas" },
  { value: "8", label: "Advogado" },
  { value: "21", label: "Agricultor" },
  { value: "37", label: "Aposentado" },
  { value: "50", label: "Assistente Administrativo" },
  { value: "64", label: "Auxiliar de Enfermagem" },
  { value: "65", label: "Auxiliar de Escritório" },
  { value: "77", label: "Bancário" },
  { value: "78", label: "Barbeiro" },
  { value: "88", label: "Cabeleireiro" },
  { value: "90", label: "Caixa" },
  { value: "100", label: "Carpinteiro" },
  { value: "123", label: "Comerciante" },
  { value: "137", label: "Contador" },
  { value: "149", label: "Cozinheiro" },
  { value: "157", label: "Dentista" },
  { value: "177", label: "Economista" },
  { value: "179", label: "Eletricista" },
  { value: "185", label: "Empregado Doméstico" },
  { value: "200", label: "Enfermeiro" },
  { value: "201", label: "Engenheiro" },
  { value: "253", label: "Funcionário Público Civil" },
  { value: "263", label: "Gerente" },
  { value: "295", label: "Jornalista" },
  { value: "344", label: "Motorista" },
  { value: "367", label: "Pedreiro" },
  { value: "392", label: "Professor" },
  { value: "548", label: "Desempregado" },
  { value: "823", label: "Sem Profissão Definida" },
  { value: "1117", label: "Do Lar/Dona de Casa" },
  { value: "1127", label: "Cuidador de Idosos" },
  { value: "1145", label: "Motorista de Aplicativo" }
];